# Generated by Django 4.1 on 2022-10-04 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dog",
            fields=[
                ("name", models.CharField(max_length=200)),
                (
                    "size",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                        max_length=200,
                    ),
                ),
                (
                    "dog_image",
                    models.ImageField(
                        blank=True,
                        default="dogs/default-dog.jpeg",
                        null=True,
                        upload_to="dogs/",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sitting",
            fields=[
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("MTL", "Montreal, Quebec"),
                            ("TOR", "Toronto, Ontario"),
                            ("VAN", "Vancouver, British Columbia"),
                            ("CAL", "Calgary, Alberta"),
                            ("OTT", "Ottawa, Ontario"),
                        ],
                        max_length=200,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sittings.dog"
                    ),
                ),
                (
                    "sitter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("price", models.IntegerField()),
                ("accepted", models.BooleanField(default=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "sitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
                (
                    "sitting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sittings.sitting",
                    ),
                ),
            ],
        ),
    ]
