# Generated by Django 4.1 on 2022-08-24 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("sittings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sitting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("MTL", "Montreal, Quebec"),
                            ("TOR", "Toronto, Ontario"),
                            ("VAN", "Vancouver, British Columbia"),
                            ("CAL", "Calgary, Alberta"),
                            ("OTT", "Ottawa, Ontario"),
                        ],
                        max_length=200,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("price", models.IntegerField()),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sittings.dog"
                    ),
                ),
                (
                    "sitter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.profile",
                    ),
                ),
            ],
        ),
    ]
