# Generated by Django 4.1 on 2022-08-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sittings",
            "0003_remove_sitting_price_alter_dog_id_alter_sitting_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitting",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
