# Generated by Django 4.1 on 2022-08-24 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sittings", "0006_offer_created_sitting_created_alter_dog_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
