# Generated by Django 4.1 on 2022-08-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sittings", "0007_dog_created"),
    ]

    operations = [
        migrations.RemoveField(model_name="dog", name="created",),
    ]
