# Generated by Django 4.1 on 2022-08-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sittings", "0008_remove_dog_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="size",
            field=models.CharField(
                choices=[("Small", "S"), ("Medium", "M"), ("Large", "L")],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sitting",
            name="location",
            field=models.CharField(
                choices=[
                    ("Montreal, Quebec", "MTL"),
                    ("Toronto, Ontario", "TOR"),
                    ("Vancouver, British Columbia", "VAN"),
                    ("Calgary, Alberta", "CAL"),
                    ("Ottawa, Ontario", "OTT"),
                ],
                max_length=200,
            ),
        ),
    ]
