# Generated by Django 4.1 on 2022-08-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sittings", "0009_alter_dog_size_alter_sitting_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="size",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sitting",
            name="location",
            field=models.CharField(
                choices=[
                    ("MTL", "Montreal, Quebec"),
                    ("TOR", "Toronto, Ontario"),
                    ("VAN", "Vancouver, British Columbia"),
                    ("CAL", "Calgary, Alberta"),
                    ("OTT", "Ottawa, Ontario"),
                ],
                max_length=200,
            ),
        ),
    ]
