# Generated by Django 4.1 on 2022-09-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sittings", "0010_alter_dog_size_alter_sitting_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="dog_image",
            field=models.ImageField(
                blank=True,
                default="profiles/user-default.png",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
